name: sample_weather
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.1
  intl: ^0.18.1
  go_router: ^12.1.0
  flutter_bloc: ^8.1.3
  lottie: ^2.3.2
  flutter_gen_runner: ^5.3.2
  freezed: ^2.3.3
  shared_preferences: ^2.2.2
  provider: ^6.1.0
  geolocator: ^10.1.0
  baseflow_plugin_template: ^2.1.2
  dio: ^5.3.3
  json_serializable: ^6.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

  colors:
    inputs:
      - assets/color/color.xml

flutter:

  uses-material-design: true

  assets:
    - assets/images/lottie/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Italic.ttf
          style: italic
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          style: normal
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
          style: italic
